// One-shot local dev setup: env files, local Postgres, schema, seed data.
//
//   npm run local:setup              # everything
//   npm run local:setup -- --env-only
//
// Only Cloudinary credentials are pulled from Railway (so photo uploads work).
// Everything else is local on purpose: a local DB, a local JWT secret, local VAPID
// keys, and no Resend key (verification/reset links are printed to the console).
import { execFileSync } from 'child_process'
import { copyFileSync, existsSync, readFileSync, writeFileSync } from 'fs'
import { randomBytes } from 'crypto'
import { createRequire } from 'module'

const root = new URL('..', import.meta.url).pathname
const backendEnvPath = `${root}backend/.env`
const frontendEnvPath = `${root}frontend/.env.development.local`
const envOnly = process.argv.includes('--env-only')

function readEnv(path) {
  if (!existsSync(path)) return {}
  const env = {}
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/)
    if (m) env[m[1]] = m[2].replace(/^["']|["']$/g, '')
  }
  return env
}

function writeEnv(path, header, vars) {
  const body = Object.entries(vars).map(([k, v]) => `${k}="${v ?? ''}"`).join('\n')
  writeFileSync(path, `# ${header}\n${body}\n`)
}

function run(cmd, args, opts = {}) {
  execFileSync(cmd, args, { stdio: 'inherit', cwd: root, ...opts })
}

// Railway vars for the linked project (optionally a specific service/environment)
function railwayVars() {
  const args = ['variables', '--json']
  if (process.env.RAILWAY_SERVICE) args.push('--service', process.env.RAILWAY_SERVICE)
  if (process.env.RAILWAY_ENVIRONMENT) args.push('--environment', process.env.RAILWAY_ENVIRONMENT)
  try {
    return JSON.parse(execFileSync('railway', args, { cwd: root, stdio: ['ignore', 'pipe', 'pipe'] }).toString())
  } catch (err) {
    const reason = err.code === 'ENOENT'
      ? 'Railway CLI not installed (brew install railway)'
      : (err.stderr?.toString().trim() || err.message)
    console.warn(`⚠ Could not read Railway variables: ${reason}`)
    return null
  }
}

const existing = readEnv(backendEnvPath)
if (existsSync(backendEnvPath) && !existsSync(`${backendEnvPath}.bak`)) {
  copyFileSync(backendEnvPath, `${backendEnvPath}.bak`)
  console.log('• Backed up existing backend/.env → backend/.env.bak')
}

const railway = railwayVars()
const CLOUDINARY_KEYS = ['CLOUDINARY_CLOUD_NAME', 'CLOUDINARY_API_KEY', 'CLOUDINARY_API_SECRET']
const cloudinary = Object.fromEntries(CLOUDINARY_KEYS.map((k) => [k, railway?.[k] ?? existing[k] ?? '']))
if (railway && CLOUDINARY_KEYS.every((k) => railway[k])) {
  console.log('• Pulled Cloudinary credentials from Railway')
} else if (CLOUDINARY_KEYS.some((k) => !cloudinary[k])) {
  console.warn('⚠ Cloudinary credentials missing — sending a fingle will fail until they are set in backend/.env')
}

// Cloudflare's published test keys: the widget always passes and siteverify accepts it
// https://developers.cloudflare.com/turnstile/troubleshooting/testing/
const TURNSTILE_TEST_SITE_KEY = '1x00000000000000000000AA'
const TURNSTILE_TEST_SECRET = '1x0000000000000000000000000000000AA'
const existingFrontend = readEnv(frontendEnvPath)

let vapidPublic = existing.VAPID_PUBLIC_KEY
let vapidPrivate = existing.VAPID_PRIVATE_KEY
if (!vapidPublic || !vapidPrivate) {
  const webpush = createRequire(`${root}backend/package.json`)('web-push')
  ;({ publicKey: vapidPublic, privateKey: vapidPrivate } = webpush.generateVAPIDKeys())
  console.log('• Generated local VAPID keys')
}

writeEnv(backendEnvPath, 'Local development — generated by `npm run local:setup`. Safe to re-run.', {
  DATABASE_URL: 'postgresql://fingle:fingle@localhost:5433/fingle',
  JWT_SECRET: existing.JWT_SECRET || randomBytes(32).toString('hex'),
  PORT: '3001',
  CLIENT_URL: 'http://localhost:5173',
  APP_URL: 'http://localhost:5173',
  ...cloudinary,
  CLOUDINARY_FOLDER: 'fingle-dev/challenges',
  VAPID_PUBLIC_KEY: vapidPublic,
  VAPID_PRIVATE_KEY: vapidPrivate,
  TURNSTILE_SECRET_KEY: existing.TURNSTILE_SECRET_KEY || TURNSTILE_TEST_SECRET,
})
writeEnv(frontendEnvPath, 'Local development — generated by `npm run local:setup`.', {
  VITE_VAPID_PUBLIC_KEY: vapidPublic,
  VITE_TURNSTILE_SITE_KEY: existingFrontend.VITE_TURNSTILE_SITE_KEY || TURNSTILE_TEST_SITE_KEY,
})
console.log('• Wrote backend/.env and frontend/.env.development.local')

if (!envOnly) {
  run('npm', ['run', 'db:up'])
  run('npm', ['run', 'db:push'])
  run('npm', ['run', 'db:seed'])
}

console.log(`
✔ Local environment ready. Start it with:  npm run dev
  App:      http://localhost:5173  (log in as alice@fingle.app / password123)
  Backend:  http://localhost:3001
  Also seeded: bob, carol, dave (same password) + a group fingle from alice to all three.
`)
